enum NotePermission {
  private
  shared
  public
}

enum NoteStatus {
  draft
  published
  archived
}

type NoteRevision @table {
  note: Note!
  version: Int!

  title: String!
  content: Any
  searchableText: String
  savedAt: Timestamp @default(expr: "request.time")
}

type Note @table {
  title: String!
  content: Any
  searchableText: String

  userUID: String!
  createdAt: Timestamp! @default(expr: "request.time")
  updatedAt: Timestamp
  deletedAt: Timestamp

  isFavorite: Boolean! @default(value: false)

  status: NoteStatus! @default(value: "draft")
  isDeleted: Boolean! @default(value: false)

  permissions: NotePermission! @default(value: "private")
  version: Int @default(value: 1)
}

type Tag @table {
  name: String! @unique
}

type NoteTag @table(key: ["note", "tag"]) {
  note: Note!
  tag: Tag!
}

type Category @table {
  name: String! @unique
}

type NoteCategory @table(key: ["note", "category"]) {
  note: Note!
  category: Category!
}